version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"    # Porta HTTP
      - "443:443"  # Porta HTTPS
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: pyramid_front
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    environment:
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}" # Para desenvolvimento local, se necessário
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    container_name: pyramid_back
    restart: always
    build: ./backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" # Para desenvolvimento local, se necessário
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    container_name: pyramid_db
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306" # Mapeia a porta do MySQL para a máquina host
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
